language: node_js
cache:
  directories:
    - node_modules
node_js:
  - node
script:
  - npm run test
after_success:
  - bash docker_push.sh
services:
  - docker
before_install:
  - docker build -t "docker-test" .
  - docker run --name "docker-test" -p 8081:8081 docker-test
  - docker ps a

